# Site settings
email: "arnav@brownfingers.com"
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-92058099-1

# SEO settings
title: Arnav Puri
description: 
url: "arnavpuri.github.io"
twitter_username: arnavpuri
default_img: 

# Profile settings
name: Arnav Puri  
profile_img: "/assets/img/profile.jpg"
profile: "Love to try new things, trying to build something"
social:
  github: http://www.github.com/arnavpuri
  twitter: https://www.twitter.com/arnavpuri

# Build settings
include: ["_categories", "_projects"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# plugins
plugins: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]

collections:
  projects:
    output: true